spring.application.name=gastos-api
server.servlet.context-path=/api/v1
spring.data.mongodb.uri=mongodb://localhost:27017/controlGastos
spring.data.mongodb.database=controlGastos

usuario=ramon
clave=asd123